botToken: 'NzMwMTI0NDQxODA3MzU1OTk1.XwS7dA.d54Frswazyw8-d9A84SZVSSTgvQ'
databaseName: 'pretronic'
botDatabaseName: 'pretronic-bot'
storage:
  address: 'deyna.ch:9877'
  username: 'discordbot'
  password: '7nNjvY5v7v,ks59RruSZSzXg#U'
  driver: 'net.pretronic.databasequery.sql.driver.SQLDatabaseDriver'
  name: 'SQL Pool-1'
  dialectName: 'MariaDB'
  useSSL: false
botOnlineStatus: ONLINE
botActivityType: WATCHING
botActivityName: "https://pretronic.net"
botActivityUrl: "https://paste.pretronic.net"
verifiedRoleId: 809488779890917418
teamRoleId: 514107237460082689
guildId: 513441444959223809
ticketLogChannelId: 685585621590605929
ticketCreateMessageId: 809865076478967880
ticketTopics:
  - name: 'DKBans'
    emoji: 693815906454732800
  - name: 'DKCoins'
    emoji: 693815987488686170
  - name: 'DKPerms'
    emoji: 693816467036045343
    roleIds: [809485026952478801, 730132219221245992]
  - name: 'General'
    emoji: 'ğŸ‡¬'
ticketCategoryId: 685585480339030029
ticketCloseEmoji: 'ğŸ”’'
ticketProvideInformationFinishEmoji: 'âœ…'
ticketProvideInformationNextTopicEmoji: 'â¡ï¸'
languages:
  - name: 'English'
    localizedName: 'en'
    default: true
    emoji: 'ğŸ‡¬ğŸ‡§'
  - name: 'Deutsch'
    localizedName: 'de'
    default: false
    emoji: 'ğŸ‡©ğŸ‡ª'
channelAutoEmojis:
  513445161846439937: ['ğŸ‘','ğŸ‘']
  513445184747339787: ['ğŸ‘','ğŸ‘']
  692052998213337101: ['ğŸ‘','ğŸ‘']
subscribeGroupEmoji:
  - messageId: 685604422080004146
    roles: ['ğŸ“£:809109531766161438', 'ğŸ“°:809109581383860244']
blogChannelIds:
  794671584669335584: 809109581383860244
blogChannelLikeEmoji: 'ğŸ‘'
blogChannelSubscribeEmoji: 'ğŸ“°'
resourceRoleIds:
  19303be6-0b2d-11eb-9f43-0242ac180002: 809485026952478801