botToken: 'NzMwMTI0NDQxODA3MzU1OTk1.XwS7dA.d54Frswazyw8-d9A84SZVSSTgvQ'
databaseName: 'pretronic'
botDatabaseName: 'pretronic-bot'
storage:
  address: 'deyna.ch:9877'
  username: 'discordbot'
  password: '7nNjvY5v7v,ks59RruSZSzXg#U'
  driver: 'net.pretronic.databasequery.sql.driver.SQLDatabaseDriver'
  name: 'SQL Pool-1'
  dialectName: 'MariaDB'
  useSSL: false
botOnlineStatus: ONLINE
botActivityType: WATCHING
botActivityName: "https://pretronic.net"
botActivityUrl: "https://paste.pretronic.net"
verifiedRoleId: 809488779890917418
teamRoleId: 514107237460082689
guildId: 513441444959223809
ticketLogChannelId: 685585621590605929
ticketCreateMessageId: 809865076478967880
ticketTopics:
  - name: 'DKBans'
    emoji: 863519915323817984
  - name: 'DKCoins'
    emoji: 863519906401091614
  - name: 'DKPerms'
    emoji: 863519925729755188
    roleIds: [809485026952478801]
  - name: 'DKFriends'
    emoji: 863519439362588703
    roleIds: [866287709349085195]
  - name: 'DKConnect'
    emoji: 863519483436072961
    roleIds: [866287822595948544]
  - name: 'DKSupport'
    emoji: 863519465588523048
    roleIds: [866287913612476438]
  - name: 'DKMotd'
    emoji: 863519398987694111
    roleIds: [866287998118133780]
  - name: 'General'
    emoji: 'ğŸ‡¬'
ticketCategoryId: 685585480339030029
ticketCloseEmoji: 'ğŸ”’'
ticketProvideInformationFinishEmoji: 'âœ…'
ticketProvideInformationNextTopicEmoji: 'â¡ï¸'
languages:
  - name: 'English'
    localizedName: 'en'
    default: true
    emoji: 'ğŸ‡¬ğŸ‡§'
  - name: 'Deutsch'
    localizedName: 'de'
    default: false
    emoji: 'ğŸ‡©ğŸ‡ª'
channelAutoEmojis:
  - channelId: 794671584669335584
    emojis: ['ğŸ‘:0', 'ğŸ“°:809109581383860244']
  - channelId: 513444967952154635
    emojis: [ 'ğŸ‘:0', 'ğŸ“£:809109531766161438' ]
  - channelId: 802240281197150238
    emojis: [ 'ğŸ‘:0', 'ğŸ“£:809109531766161438' ]
  - channelId: 513445161846439937
    emojis: [ 'ğŸ‘:0', 'ğŸ‘:0' ]
subscribeGroupEmoji:
  - messageId: 685604422080004146
    roles: ['ğŸ“£:809109531766161438', 'ğŸ“°:809109581383860244', 'ğŸ‡©ğŸ‡ª:572829252999839745', 'ğŸ‡¬ğŸ‡§:572829369203163166']
resourceRoleIds:
  19303be6-0b2d-11eb-9f43-0242ac180002: 809485026952478801
  1e6d4f31-e2e0-11eb-8ba0-0242ac180002: 866287822595948544
  9304d68a-bbdf-11eb-8ba0-0242ac180002: 866287998118133780
  a120140d-bbdf-11eb-8ba0-0242ac180002: 866287913612476438
  f9aa2e05-fb5a-407a-844c-175105ec3544: 866287709349085195