botToken: 'NzMwMTI0NDQxODA3MzU1OTk1.XwS7dA.d54Frswazyw8-d9A84SZVSSTgvQ'
databaseName: 'pretronic'
storage:
  address: 'deyna.ch:9877'
  username: 'discordbot'
  password: 'EoU)tRHzNTy9s8CnE49zI2IHr35hJU'
  driver: 'net.pretronic.databasequery.sql.driver.SQLDatabaseDriver'
  name: 'SQL Pool-1'
  dialectName: 'MariaDB'
  useSSL: false
botOnlineStatus: ONLINE
botActivityType: WATCHING
botActivityName: "https://pretronic.net"
botActivityUrl: "https://paste.pretronic.net"
verifiedRoleId: 693453056150339614
teamRoleId: 514107237460082689
guildId: 513441444959223809
pendingUserVerificationExpiry: '1w'
spigotLogin: 'Dkrieger'
spigotPassword: 'HdzouGU&Ebs&8eM90byPUiMIBjD);c'
spigotTwoFactorAuth: 'JXVHQIFIUHZV5H27'
ticketLogChannelId: 685585621590605929
ticketCreateTextChannelId: 692055652041883648
ticketCreateMessageId: 730133204933279905
ticketVerifyOpenReactionEmoji: 'âœ…'
ticketTopics:
  - name: 'General'
    emoji: 'ğŸ‡¬'
  - name: 'DKBans'
    emoji: 693815906454732800
  - name: 'DKCoins'
    emoji: 693815987488686170
  - name: 'DKPerms'
    emoji: 693816467036045343  
    resourceId: 1
ticketCategoryId: 685585480339030029
ticketCloseEmoji: 'ğŸ”’'
ticketProvideInformationFinishEmoji: 'âœ…'
ticketProvideInformationNextTopicEmoji: 'â¡ï¸'
languages:
  - name: 'English'
    localizedName: 'en'
    default: true
    emoji: 'ğŸ‡¬ğŸ‡§'
channelAutoEmojis:
  513445161846439937: ['ğŸ‘','ğŸ‘']
  513445184747339787: ['ğŸ‘','ğŸ‘']
  692052998213337101: ['ğŸ‘','ğŸ‘']
